### ISSUE TITLE
.cpp and .h files are empty

### ISSUE THREAD

**Issue by angellxp** [rickkas7/AdafruitColorTFTJoystickFeatherWing#1]
@rickkas7,

The AdafruitColorTFTJoystickFeatherWing.cpp and .h files are empty.  Can the code please be updated?

Thanks

**Comment by angellxp** [comment]
@rickkas7, Do you have the original c&h src files for this?  We cant compile it very well without it.

Thanks

**Comment by angellxp** [comment]
@rickkas7, Any updates available?  Thanks

**Comment by rickkas7** [comment]
This is a meta-library, just used to pull in the two required libraries:

```
dependencies.Adafruit_ST7735_RK=1.2.7
dependencies.Adafruit_Seesaw=0.0.3
```

The files are intended to be empty and the examples build with them empty.
